version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    command: postgres -c stats_temp_directory=/tmp

  redis:
    image: redis
    volumes:
      - ./volumes/redis-data:/data
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq

  web:
    build: .
    command: sh -c "rake db:create && rake db:migrate && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    links:
      - postgres
      - redis
      - rabbitmq
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq

  worker:
    build: .
    command: sh -c "rake sneakers:run"
    volumes:
      - .:/app
    links:
      - postgres
      - redis
      - rabbitmq
    depends_on:
      - web
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
