default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: insta_dev


test:
  <<: *default
  database: insta_test